<?php
/**
 * @file
 * Code for the UserProfile feature.
 */

include_once 'userprofile.features.inc';


/**
 * Social links in header of page.
 *
 * @return
 *   HTML output.
 */
function userprofile_header_bar() {
  $output = '';

  $menu_links = array();

  if (user_is_logged_in()) {
    global $user;
    $menu_links[] = array(
      'href' =>  'user/' . $user->uid,
      'title' => t('My profile'),
    );
    $menu_links[] = array(
      'href' =>  'user/logout',
      'title' => t('Logout'),
    );
    // Todo
    // My sessions.
  }
  else {
    $menu_links[] = array(
      'href' =>  'user/login',
      'title' => t('Login'),
    );
    $menu_links[] = array(
      'href' =>  'user/register',
      'title' => t('Register'),
    );
  }

  $output .= theme('links',  array(
                'links' => $menu_links,
                'attributes' => array('class' => array('user-links'))));

  return $output;
}

/**
 * Implements hook_form_alter().
 */
function userprofile_form_alter(&$form, &$form_state, $form_id) {
    switch ($form_id) {
      case 'user_profile_form':
        drupal_add_js(drupal_get_path('module', 'userprofile') .'/js/script.js');
        break;
      default:
        break;
    }
}